# Generated by Django 4.1 on 2022-08-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('quiz', '0002_question_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='group',
        ),
        migrations.AddField(
            model_name='quizzes',
            name='group',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
