# Generated by Django 4.1 on 2022-08-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_question_quiz_question_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='title',
            field=models.CharField(default='New Quiz', max_length=255, unique=True, verbose_name='Quiz Title'),
        ),
    ]
