# Generated by Django 4.1 on 2022-08-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('quiz', '0016_question_time_taken_to_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='group',
            field=models.ManyToManyField(related_name='quizzes', to='auth.group'),
        ),
    ]
