# Generated by Django 4.1 on 2022-08-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_alter_user_last_name_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='count_passed_tests',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='final_score',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
