# Generated by Django 4.1 on 2022-08-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_alter_user_count_passed_tests_alter_user_final_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='final_score',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
