# Generated by Django 4.1 on 2022-08-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_remove_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='final_score',
            field=models.PositiveSmallIntegerField(blank=True, default=20.0, null=True),
        ),
    ]
