# Generated by Django 4.1 on 2022-08-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_alter_question_time_taken_to_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='time_taken_to_answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_score',
            field=models.PositiveSmallIntegerField(default=100, help_text='Score for the answer'),
        ),
        migrations.AddField(
            model_name='answer',
            name='time_taken_to_answer',
            field=models.FloatField(default=20.0, help_text='Time take to answer'),
        ),
    ]
