# Generated by Django 4.1 on 2022-08-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_remove_question_time_taken_to_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_taken_to_answer',
            field=models.FloatField(default=20.0, help_text='Time take to answer'),
        ),
    ]
