# Generated by Django 4.1 on 2022-08-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_question_time_taken_to_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ManyToManyField(related_name='question', to='quiz.quizzes'),
        ),
    ]
