# Generated by Django 4.1 on 2022-08-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('quiz', '0029_alter_question_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='question',
            name='time_taken_to_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='score_max',
            field=models.FloatField(blank=True, default=100.0, help_text='Maximum score'),
        ),
        migrations.AddField(
            model_name='question',
            name='time_max',
            field=models.FloatField(default=20.0, help_text='Maximum allowed time for question'),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='group',
            field=models.ManyToManyField(related_name='group_quizzes', to='auth.group'),
        ),
    ]
