# Generated by Django 4.1 on 2022-08-22 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_remove_question_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='technique',
        ),
    ]
