# Generated by Django 4.1 on 2022-08-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0032_question_answer_core'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer_core',
            new_name='answer_score',
        ),
    ]
