# Generated by Django 4.1 on 2022-08-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_rename_answer_core_question_answer_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='question_score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
