# Generated by Django 4.1 on 2022-08-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0034_user_question_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='final_score',
            new_name='total_score',
        ),
        migrations.AddField(
            model_name='user',
            name='replied_questions_and_scores',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
