# Generated by Django 4.1 on 2022-08-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('quiz', '0035_rename_final_score_user_total_score_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quizzes',
            new_name='Quiz',
        ),
        migrations.AlterField(
            model_name='user',
            name='question_score',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
