# Generated by Django 4.1 on 2022-08-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0036_rename_quizzes_quiz_alter_user_question_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quizzes_and_answers',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
